### ISSUE TITLE
general nspires docs

### ISSUE THREAD

**Issue by timm** [ai-se/amesModels#1]
http://nspires.nasaprs.com/external/viewrepositorydocument/cmdocumentid=477038/solicitationId=%7B9927D6DC-C2F9-5D3E-8BF1-EA4EE3EE0A37%7D/viewSolicitationDocument=1/2015%20HERO%20Overview%207-31-15.pdf

**Comment by timm** [comment]
@neharungta  : in case u did not see this, plz see above

**Comment by neharungta** [comment]
This is what we were looking at yesterday.

**Comment by neharungta** [comment]
Here are some things I saw in the call
The proposal are due 
- Starting no earlier than September 4, 2015 Through no later than September 3, 2016

More on the bottom of page 4 

Details of the solicited research opportunities are given in the solicited research response area appendices of this NRA, and it is anticipated that several response area appendices will be issued throughout the year as needed. Most research opportunities will use a two-step proposal submission process, though some research opportunities may use a one-step submission process. Proposals that do not conform to the standards outlined in this solicitation will be declared noncompliant and will be handled in accordance with NASA Federal Acquisition Regulation Supplement 1815.305-70 (http://www.hq.nasa.gov/office/procurement/regs/1835.htm). Proposal due dates are given in this NRA, which will be posted at http://nspires.nasaprs.com/. Interested proposers should monitor the website or subscribe to the Human Exploration and Operations Mission Directorate electronic notifications system through their NASA Solicitation and Proposal Integrated Review and Evaluation System (NSPIRES) account for new research opportunities or amendments to this NRA through July 2016, at which time release of a subsequent HERO NRA is planned. Proposers should monitor Frequently Asked Questions (FAQs), posted alongside this solicitation, that will be updated periodically with questions and answers posed by potential investigators.

(Neha's comment: based on the two things above, I think it is better to wait until they post more amendments to their call which means more details (subtopics) for each of the topics. 

Here is The human exploration and operations directorate website: 

http://www.nasa.gov/directorates/heo/home/#.VciwZUUdiEw

The best bet for us seems: 

Appendix A: NASA Research and Technology Development to Support Crew Health and Performance in Space Exploration Missions - proposals are solicited that address specific research emphases of the Behavioral Health and Performance, Human Health Countermeasures, and Space Human Factors and Habitability Elements. Unless otherwise noted, these projects are expected to be multiple- year efforts.

(Neha's comment: I think the ones that say multiple- year efforts is better)

**Comment by neharungta** [comment]
The appendices have not been updated since 2014 but say that for the call: http://nspires.nasaprs.com/external/solicitations/summary.do?method=init&solId={48135788-4986-9DF9-9C3C-D58012CEB899}&path=open that ends on Sept 30th, 2015.  If you want to propose immediately, it should be to the (NNJ14ZSA001N) call.

**Comment by neharungta** [comment]
The monies is too little for me to be able to participate in the proposal as a co-I. But there are two things we can do to alleviate that (1) Put me for some X hours as a consultant and (2) we do the work and hopefully AERO funds me and HERO funds you!

**Comment by timm** [comment]
I'm kinda asking if the sept4 thing is stage1 of a 2 stage process where state1 is some lightweight letter of intent.

which would make all our workloads less tense

**Comment by neharungta** [comment]
My understanding is there is nothing to be done for Sept4 2015. This is when things open for submission.
